# Generated by Django 4.2.1 on 2023-05-24 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='diary',
            name='edited',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
